apiVersion: apps/v1
kind: Deployment
metadata:
  name: rif07-results
  namespace: challenge-adinusa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
      - name: results
        image: registry.adinusa.id/project-kubernetes-bootcamp/rif07:result-v1
        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - secretRef:
            name: rif07-database-secret

---
apiVersion: v1
kind: Service
metadata:
  name: rif07-results-svc
  namespace: challenge-adinusa
spec:
  selector:
    app: results
  ports:
  - port: 80
    targetPort: 80
